### ISSUE TITLE
NPM package version

### ISSUE THREAD

**Issue by jonathan-aurelia** [toomuchdesign/next-use-contextual-routing#21]
## 💬 Questions and Help
The latest version on the [NPM page is v2.3.0](https://www.npmjs.com/package/next-use-contextual-routing) but it looks as though there should be a [v3.0.0](https://github.com/toomuchdesign/next-use-contextual-routing/releases/tag/v3.0.0) available based on the releases and the description of next@13 support in this repo's README.

Could you advise as to next steps?

**Comment by toomuchdesign** [comment]
Hi @jonathan-aurelia, thanks for pointing out! v3.0.0 is now available on NPM 👍
