### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tahola** [toomuchdesign/next-use-contextual-routing#22]
Hello guys, since I updated to Next 13.2.4 and next-use-contextual-routing from 2.3.0 to 3.0.0, I am getting this error every time I want to import the package `import { useContextualRouting } from 'next-use-contextual-routing';`
 
```
/node_modules/next-use-contextual-routing/dist/index.js:1
import { useCallback } from 'react';
SyntaxError: Cannot use import statement outside a module
```

packages.json
```
"dependencies": {
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.16",
    "@next/font": "13.1.1",
    "@react-oauth/google": "^0.5.1",
    "@types/node": "18.11.18",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.10",
    "axios": "^1.3.2",
    "eslint": "8.31.0",
    "eslint-config-next": "13.1.1",
    "js-cookie": "^3.0.1",
    "next": "13.2.4",
    "next-pwa": "^5.6.0",
    "next-use-contextual-routing": "^3.0.0",
    "nprogress": "^0.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.8.0",
    "react-intersection-observer": "^9.4.1",
    "react-toastify": "^9.1.1",
    "react-twitter-embed": "^4.0.4",
    "react-web-share": "^2.0.2",
    "typescript": "4.9.4",
    "zustand": "^4.3.6"
  },
  "devDependencies": {
    "@tailwindcss/line-clamp": "^0.4.2",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.20",
    "tailwindcss": "^3.2.4"
  }

```

Any help ?

**Comment by ffrancisco-rosa** [comment]
Hi there.

I had the same problem.

As a temporary solution what i did was to use **dynamic** import with **ssr:false.**
This makes it so Next.js skips server-side run.
Because of this functional component where I am using the useContextualRouting hook stops having that error.

Don't know the intrinsic details of problem cause/solution but that is what worked ;)

**Comment by tahola** [comment]
Thank you @ffrancisco-rosa , not the best solution but it will do, would you mind to share some code ?

**Comment by ffrancisco-rosa** [comment]
Sure thing.
You can extend it all you want of course.

```
const LinKExample = () => {
    const { makeContextualHref } = useContextualRouting();
    return (
        <Link
            href={makeContextualHref({ id: 33 })}
            as="/route-to-visit-contextually"
            shallow
        >
            Label
        </Link>
    )
}

// where you want to use the link component
const DynamicLinkExample = dynamic(() => import('path/to/link/example'), { ssr: false });
const Page = () => {
    return (
        <>
            <DynamicLinkExample />
        </>
    )
}
```

**Comment by tahola** [comment]
Thank you but where do you `import { useContextualRouting } from "next-use-contextual-routing";` ? 
If I create a component like you did I still have to import it and I still get the error :

```
import { useContextualRouting } from "next-use-contextual-routing";
import Link from "next/link";
const dynamicLink = () => {
  const { makeContextualHref } = useContextualRouting();
  return (
    <Link
      href={makeContextualHref({ id: 33 })}
      as="/route-to-visit-contextually"
      shallow
    >
      Label
    </Link>
  );
};

export default dynamicLink;

```

**Comment by tahola** [comment]
Thank you but where do you `import { useContextualRouting } from "next-use-contextual-routing";` ? 
If I create a component like you did I still have to import it and I still get the error :

```
import { useContextualRouting } from "next-use-contextual-routing";
import Link from "next/link";
const dynamicLink = () => {
  const { makeContextualHref } = useContextualRouting();
  return (
    <Link
      href={makeContextualHref({ id: 33 })}
      as="/route-to-visit-contextually"
      shallow
    >
      Label
    </Link>
  );
};

export default dynamicLink;

```

**Comment by tahola** [comment]
Thank you but where do you `import { useContextualRouting } from "next-use-contextual-routing";` ? 
If I create a component like you did I still have to import it and I still get the error :

```
import { useContextualRouting } from "next-use-contextual-routing";
import Link from "next/link";
const dynamicLink = () => {
  const { makeContextualHref } = useContextualRouting();
  return (
    <Link
      href={makeContextualHref({ id: 33 })}
      as="/route-to-visit-contextually"
      shallow
    >
      Label
    </Link>
  );
};

export default dynamicLink;

```

**Comment by tahola** [comment]
Thank you but where do you `import { useContextualRouting } from "next-use-contextual-routing";` ? 
If I create a component like you did I still have to import it and I still get the error :

```
import { useContextualRouting } from "next-use-contextual-routing";
import Link from "next/link";
const dynamicLink = () => {
  const { makeContextualHref } = useContextualRouting();
  return (
    <Link
      href={makeContextualHref({ id: 33 })}
      as="/route-to-visit-contextually"
      shallow
    >
      Label
    </Link>
  );
};

export default dynamicLink;

```

**Comment by tahola** [comment]
@ffrancisco-rosa Never mind I was also importing from my page, now its working, thank a lot for your help and sorry for the spam Github went crazy :)

**Comment by tahola** [comment]
Yes it still an issue.

**Comment by toomuchdesign** [comment]
Thanks @tahola and @ffrancisco-rosa ! Would you be able to provide a minimal repro to facilitate debugging?

**Comment by tahola** [comment]
@toomuchdesign just did one with basic **next-create-app** and **next-use-contextual-routing** : [https://github.com/tahola/next-use-contextual-routing-test]( https://github.com/tahola/next-use-contextual-routing-test)

**Comment by tahola** [comment]
If it can help, when I put the index.ts in my hooks folder (hooks/useContextualHref.ts) I can import it and use it without any issues.

**Comment by toomuchdesign** [comment]
A solution might consist of compiling the package to commonJS, not sure what's the expected format, now.

**Comment by tahola** [comment]
I wasnt able to do it so I created a hook in typescript, its the only one in typescript in my project but it work and at least I can use it the same way without modifying my code everywhere.

/hooks/useContextual.ts
`import { useCallback } from "react";
import { useRouter } from "next/router";
import stringify from "qs-stringify";
export const RETURN_HREF_QUERY_PARAM = "_UCR_return_href";

/**
 * During contextual routing browser URL will be controlled by Next Router's "as" prop
 * while the page actually rendered is defined by Next Router's "href" prop.
 *
 * During contextual navigation Next Router's behaves as follows:
 * router.asPath:   /item/3               reflects current URL and updates at each page change
 * router.pathname: /search/[terms]       stay the same as long as initial page doesn't change
 * router.query:    {"terms": "foo-bar"}  same as above
 */
export function useContextualRouting(): {
  returnHref: string,
  makeContextualHref: (extraParams?: Record<string, string | number>) => string,
} {
  const router = useRouter();
  const returnHrefQueryParam =
    typeof router.query[RETURN_HREF_QUERY_PARAM] === "string"
      ? router.query[RETURN_HREF_QUERY_PARAM]
      : undefined;
  const watchedQuery = Object.assign({}, router.query);
  delete watchedQuery[RETURN_HREF_QUERY_PARAM];

  /*
   * After a page refresh there is no RETURN_HREF_QUERY_PARAM in router.query
   * RETURN_HREF_QUERY_PARAM is only available in those history entries where
   * contextual navigation is enabled (or WAS enabled in case history.back() is triggered)
   */
  const returnHref = returnHrefQueryParam ?? router.asPath;
  // @NOTE JSON.stringify might be replaced with any hashing solution
  const queryHash = JSON.stringify(watchedQuery);
  const makeContextualHref = useCallback(
    (extraParams?: Record<string, string | number>) =>
      router.pathname +
      "?" +
      stringify(
        Object.assign({}, router.query, extraParams, {
          [RETURN_HREF_QUERY_PARAM]: returnHref,
        })
      ),
    [queryHash, returnHref]
  );

  return { returnHref, makeContextualHref };
}
`

mypage.js
`import { useContextualRouting } from "../../hooks/useContextual";
`
