### ISSUE TITLE
New in Next.js: Parallel Routes and Interception

### ISSUE THREAD

**Issue by leerob** [toomuchdesign/next-use-contextual-routing#25]
Thank you so much for this library. You might enjoy the new features we'd added to Next.js 🙏 Open to feedback.

https://nextjs.org/blog/next-13-3#parallel-routes-and-interception

**Comment by toomuchdesign** [comment]
Hi @leerob, I understand that intercepting routes should be able to replace this package. If so, happy to deprecate it in favour of native routes.

**Comment by leerob** [comment]
If you feel the native support matches everything you wanted to accomplish, then yes! Also open to feedback on the implementation and experience since you have a lot of experience in this area.

**Comment by prince272** [comment]
Hello @leerob, Thanks for leaving this message here. Also thank you so much for this library, it has been very useful in some of my personal project that I worked on.

**Comment by toomuchdesign** [comment]
Project deprecated!
