### ISSUE TITLE
Please re-active this repo

### ISSUE THREAD

**Issue by phatify** [toomuchdesign/next-use-contextual-routing#27]
Hi author. First of all I am very appreciated to this repo. But  please re-maintain this repo.  it's still useful for `pages/` dir, not just `/app` dir.

**Comment by toomuchdesign** [comment]
Hi @phatify, what exactly is still not possible to do with native Next routing? I haven't used Next.js during the last couple years, so I'd need some support/advise.

**Comment by noveogroup-amorgunov** [comment]
Hi @toomuchdesign +1 for reactive this repo. App Router don't solve with returnHref.

They have example https://nextgram.vercel.app/, but this one don't show how to solve problems. If we have navigation into modals (one modal can open another), we need same approach which you provide with this library

**Comment by toomuchdesign** [comment]
@noveogroup-amorgunov Have you had a chance to test this library against newer Next versions (14 / 15)?

**Comment by noveogroup-amorgunov** [comment]
> @noveogroup-amorgunov Have you had a chance to test this library against newer Next versions (14 / 15)?

@toomuchdesign yes I will test it and come back

**Comment by toomuchdesign** [comment]
Opened to support Next v13 and v14, and tests seem fine.

Project undeprecated 👍
