### ISSUE TITLE
Update page title for modal URL

### ISSUE THREAD

**Issue by rrjanbiah** [toomuchdesign/next-use-contextual-routing#6]
## 🚀 Feature Proposal

I think, changing the page title based on the URL change will be good.

**Comment by toomuchdesign** [comment]
Hi @rrjanbiah,
do you refer to the demo or the library itself?

**Comment by rrjanbiah** [comment]
@toomuchdesign Thanks for your reply. Yes, referred the demo. Is this available already?

**Comment by toomuchdesign** [comment]
I see. Title change in the demo could be a nice plus even though not related with the responsibilities on this library. Would you open a PR?

Greetings!
