### ISSUE TITLE
"next-use-contextual-routing" not install work in next js 15.0.0 version

### ISSUE THREAD

**Issue by Par-Nitin1** [toomuchdesign/next-use-contextual-routing#86]
npm error code ETARGET
npm error notarget No matching version found for next@^13.0.0 | ^14.0.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\PC\AppData\Local\npm-cache\_logs\2024-10-22T13_00_02_874Z-debug-0.log

**Comment by toomuchdesign** [comment]
Hi @Par-Nitin1,
Next.js v15 is not supported, yet.
