### ISSUE TITLE
Scroll behaviour on Safari

### ISSUE THREAD

**Issue by enkhtulga** [toomuchdesign/next-use-contextual-routing#9]
## 🐛 Bug Report

I have faced an issue related to scroll behaviour on Safari (14.1 version). When i use to 
```bash
const openModal = () => router.push(makeContextualHref({ pathName: SAMPLE }), SAMPLE, { shallow: true })
```
for open modal, then scroll is not working on Safari. 

## Expected behavior

Scroll is working properly on Safari.

**Comment by toomuchdesign** [comment]
Hi @enkhtulga,
we should ensure that the issue is caused by `next-use-contextual-routing` itself. Is scroll broken if you open the modal with a plain `router.push` call?
